### ISSUE TITLE
Create a new repository for OpenIoMeT website 

### ISSUE THREAD

**Issue by kumarrishav** [OpenIoMeT/iomet#1]

**Comment by kumarrishav** [comment]
Here the repo for OpenIoMeT website
https://github.com/OpenIoMeT/openiomet.github.io

As of now, this website is a static page and will use google forms to interact and take input from people.
Feel free to comment and add your valuble suggestions.

**Comment by kaichih** [comment]
How about creating a Github page for this repository? Then, people can open the web site there.

**Comment by kumarrishav** [comment]
Are you talking about openiomet.github.io? It's already there.

**Comment by kumarrishav** [comment]
I already made the website. https://openiomet.github.io

**Comment by snowmantw** [comment]
Since it has been done I close the issue. Thanks @kumarrishav .
