### ISSUE TITLE
Inform previous contributors/signup about this updates and changes

### ISSUE THREAD

**Issue by kumarrishav** [OpenIoMeT/iomet#10]
@kaichih Once we get basic stable structure of project done (hopefully by this month),  can you mail all our previous signups/contributors about this new update like a brief mail about new website, Wiki, resources etc ? 
Signups/contributors info like name, email are available in our previous google sheet. This will help in on boarding more contributors.

What you say? @snowmantw @kaichih  

Thanks

**Comment by gangit** [comment]
Hi All,

FYI

While exploring information about open medical devices, I came across this
interesting site:

http://www.fondationpierrefabre.org/

http://www.fondationpierrefabre.org/fr/suivre-notre-action/echopen-lancement-du-premier-prototype-dechostethoscope-open-source-low-cost

Sorry most of the information is in french. However I hope the projects
will interest you.

Thanks,

Best

Ganesh

**Comment by kaichih** [comment]
@kumarrishav , I think we need to do it by the end of milestone 1. Assigned this issue to me, and assigned the milestone. Please help to enumerate what should be done before I send out the notification, and feel free to assign these issues into milestone 1. 

Thanks.

**Comment by kaichih** [comment]
This issue is related to: #12 , #14 , #13 and #2 .

**Comment by kaichih** [comment]
Will do it as soon as we agree to start milestone 2.

**Comment by kaichih** [comment]
Done. Just sent an email to our Google Group.
