### ISSUE TITLE
Gitter - Update chat room - https://gitter.im/OpenIoMeT/updates

### ISSUE THREAD

**Issue by kumarrishav** [OpenIoMeT/iomet#11]

**Comment by kumarrishav** [comment]
**Formats for publishing updates on [Updates channel](https://gitter.im/OpenIoMeT/updates)**

Use Markdown syntax. 

Refrain yourself from doing chat in this room. Discuss once with organisation admin before publishing.

Weekly Meeting will be done on [General/Management Discussion Channel](https://gitter.im/OpenIoMeT/iomet)
Engineering specific meeting will be done on [Engineering/Technical Discussion Channel](https://gitter.im/OpenIoMeT)

Sample formats : 

**Format - 1**
_@/all Agenda for weekly meeting - 26th Aug 2016_
1. your agendas
2. ......
3. ......

**Format - 2**
_@/all Minutes of meeting for weekly meeting - 26th Aug 2016_
1. Mintues of meeting
2.....
3.....

**Format - 3**
_@/all Announcement -  Weather-shimmer available for use_
1. Read the README.md for various APIs https://github.com/OpenIoMeT/Weather-shimmer
2.....
3.....

P.S if you are using some new category for updates. Please update on this issue too.

**Comment by gangit** [comment]
Hi All,

During the talk  we had today, I mentioned about a foundation. I am pleased
to share with you the english version of the website. Here are few
interesting  links:

http://www.fondationpierrefabre.org/en/our-programmes/access-quality-healthcare/creation-of-e-health-observatory

http://www.fondationpierrefabre.org/en/suivre-notre-action/echopen-first-low-cost-open-source-ultrasound-stethoscope-prototype-launched

http://www.fondationpierrefabre.org/en/current-initiatives

Best,
Ganesh

**Comment by kaichih** [comment]
@kumarrishav , I was thinking to use Wiki to record down our agreed meeting minutes. What do you think?

**Comment by kumarrishav** [comment]
Agree. Also, it will be nice if you mention all these in our wiki, before its implementation.

**Comment by kaichih** [comment]
Good. I will close this issue for now. I will work on this.

**Comment by kaichih** [comment]
Refer to #14
