### ISSUE TITLE
To manage and track our works periodically, by using "milestone"

### ISSUE THREAD

**Issue by kaichih** [OpenIoMeT/iomet#12]
We talked about sprint management, and how we should track all our works. Since we all agreed to use Github issues to manage our works, including management and engineering items, we shouldn't use another system to track these items due to duplicated management efforts. So, I would like to propose to use "milestone" in Github to manage this part. 

So, we can have the milestone agreed by all of us. It can be monthly milestones and we can have a short name for each milestone. For example, the first one I created is named "basic framework" with deadline = Sep 30 because it would be the highest priority for all of us to work on this project. So, once we agreed this is the next milestone, we can start to assign what issues should be resolved in this milestone. Then, with this field, we can realize what should be done in what kinds of timeline. It's just like sprint management. However, 2 weeks as a sprint might be too short for anyone who has daily job just like us. So, we can start to use a month as a sprint so far. Then, we can see if we should change that in the future. 

Therefore, in the future, during weekly meetings, we can review the open issues under specific milestone and see if there is anything we need help from others, and/or discuss the next milestones. 

@snowmantw , @kumarrishav , what do you think? If you guys agree, then we can close this issue. Thank you.

**Comment by kaichih** [comment]
I assigned some issues into the first milestone, and we can list down all issues that we need to resolve in this milestone by visiting the link of the milestone: 
https://github.com/OpenIoMeT/Iomet-wiki/milestone/2

**Comment by kumarrishav** [comment]
I liked the milestone feature :) to manage our sprint.

**Comment by kumarrishav** [comment]
Also, please close the issues which we already addressed. 
For example: https://github.com/OpenIoMeT/Iomet-wiki/issues/2 
Now we can have Milestone - 1, Milestone - 2  etc. instead of roadmap. So, this issue can be closed with a closing comment. 
I am really loving this milestone feature. I wasn't aware of this feature before.
Thanks.

**Comment by kaichih** [comment]
Thanks, Kumar. Also please feel free to add whatever you think you can own and finish in this milestone by tagging the milestone to issues.
