### ISSUE TITLE
A channel for our weekly regular meetings

### ISSUE THREAD

**Issue by kaichih** [OpenIoMeT/iomet#13]
We should have a voice channel that allows us to have our regular meetings. Do you guys think Gitter is enough now? Maybe it's a good way now, because we have our daily job and it might be not easy for all of us to join in a voice meeting. I think it's worthy to get all of your agreements here. 

Or, if most of us would like to have a place for us to dial in and speak, maybe we can have a Skype group, and we can call the whole group for regular meetings. 

Ping @snowmantw and @kumarrishav to see how you guys think.

**Comment by kumarrishav** [comment]
Yeah, Skype/Hangouts looks good to me. I am okay with it But if someone is not able to join skype/hangout, then we should update same on gitter too in parallel.

I too felt, doing meeting on gitter has some friction.

**Comment by kaichih** [comment]
I crated a Skype group here: 
https://join.skype.com/ccWbIRaE5vbw

**Comment by kaichih** [comment]
Let me close the issue for now. I will update the link and paste it to our Wiki. If it doesn't work, let's find other solutions.

**Comment by kaichih** [comment]
Added to the Wiki: https://github.com/OpenIoMeT/Iomet-wiki/wiki
