### ISSUE TITLE
Management of meeting minutes

### ISSUE THREAD

**Issue by kaichih** [OpenIoMeT/iomet#14]
Also, we should have a way to manage all our meeting minutes. @kumarrishav , I think it's not a good idea to put our meeting minutes in Gitter, because Gitter is designed like chat rooms. I am thinking that, maybe we can have our meeting minutes in the Wiki of Github. Then, we can have more information completed in one single place: Github. What do you think?

**Comment by kumarrishav** [comment]
Yes, I am agree with you. As things were not planned that's why i updated on gitter. Also @snowmantw was planning to build bots which will do our work like publishing meeting minutes on github. Also, Before implementing these, we should clear our rules/structure on Wiki. So, that a person can refer this to understand our org and it's working , say, how we do meeting, where we do put minutes of meeting etc.

**Comment by kaichih** [comment]
Cool. I can start with some examples on the wiki and we can see how we should improve in the future.

**Comment by kaichih** [comment]
I am feeling that, it's somehow a little bit unproductive for us to put meeting minutes to the Wiki. I mean, if there is a place for us in our meeting, and everyone of us can type/input whatever we are going to say at the same time, it would be better. Just like etherpad, or Google doc. Maybe during the meeting, we can have our agenda in a Google Doc, just like what we had before. Then, maybe we can keep our meeting notes there, too?

**Comment by kaichih** [comment]
I am sorry to change the proposal again. I think Google Doc should be much better. That's based on how we should have our meeting going. It can be used during the meeting, in ad-hoc mode, meaning, everyone of us can edit the same document simultaneously. It would be much productive.

**Comment by kaichih** [comment]
I created a Google Doc here: 
https://docs.google.com/document/d/197l6VVDVQ7VlsLUBY8k9CF2KsrnP2Y3ifEXgCAAU5Is/edit?usp=sharing
Let's try to use it for our next meeting this week.

**Comment by kaichih** [comment]
This one should be already completed. Close this issue for now. Please feel free to reopen it if it is needed. Thanks,
