### ISSUE TITLE
Add road maps for iomet (or OpenIoMeT) to Wiki

### ISSUE THREAD

**Issue by kumarrishav** [OpenIoMeT/iomet#2]
-  Update the Wiki with our short term and long term goals after discussion with team members. We can initiate the discussion here.
-  Create the timeline to achieve shorter goals first.

**Comment by kaichih** [comment]
Should we identify some technical dependencies and record them down first? @snowmantw?

**Comment by snowmantw** [comment]
I think to consider a timeline according to what we may complete in this half year is a good start. And, I feel we need to put the previous demo project as our short-term goal to make todo items more clear to us.

If things go well, I think we may have the workable demo in September, which includes separated services that in different repo and collaborate together:
- iomet-reactor: the core analyser
- iomet-crawler: to fetch external data per request
- iomet-monitor: to command & monitor all services under one commander
- iomet-gateway: to provide API & webservice

We will rely on external services like:
- postgresql: general db backend
- zeromq: the async message queue for service communication
- mhealth-shimmer: for device registration and data feeding

We can wrap these external services for better control and maintenance. However, the first 4 services would be done by us. I will update progress while they're implemented one-by-one.

**Comment by kumarrishav** [comment]
Assigning to @kaichih . Once we finalize the roadmap and comment here in detail, you can update same on Wiki.

**Comment by kaichih** [comment]
I am thinking to use "milestone" to represent our roadmap. Please refer to #12 

So, once a milestone is created, everyone can put whatever he or she is comfortable to finish in this milestone by assigning this milestone to corresponding issues. So, it's managed by all of us. BUT, each milestone should have a major theme. And, the length of milestone could be a month, or 2 months, or a quarter. But, usually, maybe we should have it monthly.

**Comment by kaichih** [comment]
Good. I will close this issue, because we can use milestone in Github to represent our road map of this project. I think we can add one more Wiki page to represent all milestones we have. Then, people can know our overall plan.
