### ISSUE TITLE
Few initial requirements to start this project.

### ISSUE THREAD

**Issue by kumarrishav** [OpenIoMeT/iomet#3]
- Purchase server. AWS is a good option. We can discussion in this issue about how to go with it like expense and all.
- IMO we shouldn't worry about project name as of now. Though **iomet** looks too generic, it's fine for now. At later stage we might come with better name (if required). What do you say? 
- Minimum 1-2 people support in each field (Front End and Back End developers, Q/A & Testers, Security experts, UI/UX and Visual designer, Medical experts etc) who can devote their time to this. Obviously we will be happy to see if we can get more and more people :smile:  

Feel free to add comments and suggestion

**Comment by kaichih** [comment]
For item 2, yes. I think we should come out a better name. Actually, Eir looks good to me. But, of course, we can try to find other good names.

**Comment by kaichih** [comment]
For item 3, of course. If you or anyone who see any other persons who are interested in joining us, please invite them and add them to this Github.

**Comment by kumarrishav** [comment]
I think most of these are done/in process (like adding new people). 
Closing this issue.
