### ISSUE TITLE
Issue to track changes in Wiki or README

### ISSUE THREAD

**Issue by kumarrishav** [OpenIoMeT/iomet#5]
This issue is to track changes in Wiki and README. If you want to add or modify something in these files, feel free to send pull requests. Just mention here what changes you did or doing and why.

P.S - I created this issue because there might be the people like me who is not good at language. So feel free to modify and add stuff to these files.

**Comment by kumarrishav** [comment]
While going through Mozilla Wiki and Github Wiki,I found till **Architecture**  everything is moved to github wiki. Thanks @kaichih for that.

I think we can move these sections too :-  **Data sources**,  **Vital Signs**  (under research section or something similiar), **Communication Channels** (under communication, obviously we need new communication channel, like freenode for new irc channel, goggle group is already there, Online Meeting channel, gitter chat etc), **Medical Consultant(s)**,  **Reference** . Also we should collect all links at one place under github wiki ..

_OLD-Signup link/Members, User stories_,Reference https://docs.google.com/spreadsheets/d/1kWzx8lcZcOLkVB2Ie79zzVNHWEIt9mUL7jgWOkeD3i4/

_OLD-Research and planning for Phase 1 prototyping_
https://docs.google.com/document/d/1a_gEkA4mY9ednxD4EuN34cAhk8eDILrzd3wQsJMXqXs/

_OLD- Meeting Notes_
https://docs.google.com/document/d/1TQRfJYBNp8qO8oLx5gsah2Fy4dlapBXWXur2KzxXa84/

_OLD- Trello board_
https://trello.com/b/4u8xVI4a/fxos-medical-platform

_OLD-Bugzilla Meta_
https://bugzilla.mozilla.org/show_bug.cgi?id=1223309 

Others section of Mozilla Wiki like **Bug list** (I guess,we don't need this anymore,so these should be closed. Of course we can use it as a reference for future work like filing new issues), **Team members** (Either we don't need this now or need a updated on because as per wiki, lots of people are there but not active anymore. May be because of  project was not active. Also Github already contributors or team members section. So, no need to write this explicitly, IMO), **WorkWeeK Meetings** (not sure about this) 

I believe Kevin can take good care of documentation and editing wiki stuff (he is much better than me on language)

Also, IMO we shouldn't move everything to wiki. Some sections like Contribution.md, General coding style, code of conduct,  communication channel etc can be on README. Wiki is good place to tell about project, concept, architecture, Road Maps etc.

Suggestions are welcome @kaichih @snowmantw  .

**Comment by kumarrishav** [comment]
Once we have these, we don't need to be depend on MozillaWiki anymore.

**Comment by kaichih** [comment]
I am happy to work on this one.

**Comment by kumarrishav** [comment]
Closing this one as we are already on this track
